/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.lowagie.text.DocumentException;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.ConexaoBanco;
import model.Professor;
import model.ProfessorDao;
import model.relatorio;

/**
 *
 * @author Douglas Oliveira
 */
public class EditarProfessor extends javax.swing.JFrame {
    DefaultTableModel tmProfessor = new DefaultTableModel(null, new String[]{"Id", "Nome", "Cpf", "Endereço","Telefone", "Salario"}){  
          public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            }  
        };
    List<Professor> professores;
    ListSelectionModel lsmProfessores;
    DefaultListModel model = new DefaultListModel(); 
    /**
     * Creates new form EditarProfessor
     */
    public EditarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTPesquisa = new javax.swing.JTextField();
        jBPesquisa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labeEnd = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTcpf = new javax.swing.JTextField();
        JTid = new javax.swing.JTextField();
        JTnome = new javax.swing.JTextField();
        JTend = new javax.swing.JTextField();
        JTtel = new javax.swing.JTextField();
        JTsalario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAulasDadas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setTitle("VISUALIZAR/EDITAR PROFESSOR");
        setResizable(false);

        jTTabela.setModel(tmProfessor);
        jTTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmProfessores = jTTabela.getSelectionModel();
        lsmProfessores.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if (! e.getValueIsAdjusting()){
                    jTTabelaLinhaSelecionada(jTTabela);
                }
            }
        });
        jScrollPane1.setViewportView(jTTabela);

        jLabel1.setText("NOME:");

        jBPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Magnifying-Glass-black-48.png"))); // NOI18N
        jBPesquisa.setText("Pesquisar");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelNome.setText("NOME:");

        labeEnd.setText("END.:");

        labelTel.setText("TEL.:");

        labelSalario.setText("SALARIO:");

        labelId.setText("ID:");

        jLabel7.setText("CPF:");

        JTid.setEditable(false);

        jScrollPane2.setViewportView(jListAulasDadas);

        jLabel2.setText("AULAS DADAS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTel)
                    .addComponent(labeEnd)
                    .addComponent(labelNome)
                    .addComponent(labelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTtel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(labelSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTsalario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTnome)
                    .addComponent(JTend))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelId)
                                .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeEnd)
                            .addComponent(JTend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSalario)
                            .addComponent(labelTel)
                            .addComponent(JTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/delete-128.png"))); // NOI18N
        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Save-256.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Pdf-32.png"))); // NOI18N
        jButton3.setText("Gerar Relatorio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        try {
            // TODO add your handling code here:
  
            listarProfessores();
        } catch (Exception ex) {
            Logger.getLogger(EditarProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            alteraProfessor();
            listarProfessores();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema no Altera"+ex);
        } catch (Exception ex) {
            Logger.getLogger(EditarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
{
        
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      if (jTTabela.getSelectedRow() == -1) {
          
          JOptionPane.showMessageDialog(null, "Selecione um professor !");
      } else{ 
        relatorio doc = new relatorio();
        try {
            doc.getRelatorioProfessor(JTid.getText());
        } catch (DocumentException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } 
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTTabela.getSelectedRow() != -1) {
                  try {
            
            excluirProf();
            mostraPesquisa(professores);
            listarProfessores();
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Erro ao Excluir: professor esta atrelado a uma aula");
        } catch (Exception ex) {
            Logger.getLogger(EditarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else {
        JOptionPane.showMessageDialog(null, "Selecione um professor para excluir");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTcpf;
    private javax.swing.JTextField JTend;
    private javax.swing.JTextField JTid;
    private javax.swing.JTextField JTnome;
    private javax.swing.JTextField JTsalario;
    private javax.swing.JTextField JTtel;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jListAulasDadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTable jTTabela;
    private javax.swing.JLabel labeEnd;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelTel;
    // End of variables declaration//GEN-END:variables

        public void excluirProf() throws SQLException, Exception {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse professor?",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            ProfessorDao dao = new ProfessorDao();
            dao.excluir(professores.get(jTTabela.getSelectedRow()));
            mostraPesquisa(professores);
        }
    }

    private void listarProfessores() throws Exception {
        
       ProfessorDao dao = new ProfessorDao();
       professores = dao.consultarTodos("%" + jTPesquisa.getText()+ "%"); 
       mostraPesquisa(professores);
        
  
    }
    
    private void mostraPesquisa(List<Professor> professores) {
     while(tmProfessor.getRowCount()>0){
            tmProfessor.removeRow(0);
        }
      if(professores.isEmpty()){
          JOptionPane.showMessageDialog(null, "Nenhum professor cadastrado!");
      }else{
          String[] linha = new String[] {null, null, null, null, null, null};
          for (int i = 0; i < professores.size(); i++) {
              tmProfessor.addRow(linha);
              tmProfessor.setValueAt(professores.get(i).getIdProf(), i, 0);
              tmProfessor.setValueAt(professores.get(i).getNome(), i, 1);
              tmProfessor.setValueAt(professores.get(i).getCpf(), i, 2);
              tmProfessor.setValueAt(professores.get(i).getEndereco(), i, 3);
              tmProfessor.setValueAt(professores.get(i).getTelefone(), i, 4);
              tmProfessor.setValueAt(professores.get(i).getSalario(), i, 5);
          }
      }  
    }

    
    private void jTTabelaLinhaSelecionada(JTable tabela){
        if (jTTabela.getSelectedRow() != -1) {
            habilitaDados();
            JTid.setText(String.valueOf(professores.get(tabela.getSelectedRow()).getIdProf()));
            JTnome.setText(professores.get(tabela.getSelectedRow()).getNome());
            JTend.setText(professores.get(tabela.getSelectedRow()).getEndereco());
            JTtel.setText(professores.get(tabela.getSelectedRow()).getTelefone());
            JTsalario.setText(String.valueOf(professores.get(tabela.getSelectedRow()).getSalario()));
            JTcpf.setText(String.valueOf(professores.get(tabela.getSelectedRow()).getCpf()));
            popularList();

            
        } else {
            limparCampos();
            model.removeAllElements();   
            jListAulasDadas.setModel(model);

        }

 
}
    public void popularList (){
        model.removeAllElements();   
        jListAulasDadas.setModel(model);  
        
        PreparedStatement stmt = null;
        Connection conn = null;
        
        try {
            conn = ConexaoBanco.getAbreConexao();
            stmt = conn.prepareStatement("select aula.horario, aula.nome from professor\n" +
                                         "inner join aula\n" +
                                         "on aula.id_prof = professor.id_prof\n" +
                                         "where professor.id_prof = "+ JTid.getText());
            ResultSet rs = stmt.executeQuery();

            
            
            while ( rs.next()){
                String aulas = rs.getString("horario")+" - "+rs.getString("nome");
                model.addElement(aulas);
  
               
            }
            }   catch (SQLException | HeadlessException e ) {
            JOptionPane.showMessageDialog (null, " Erro   \n" +e);
        }
    
    } 

     public void habilitaDados(){
        JTnome.setEditable(true);
        JTend.setEditable(true);
        JTtel.setEditable(true);
        JTsalario.setEditable(true);
        JTcpf.setEditable(true);
        
        JTnome.setEnabled(true);
        JTend.setEnabled(true);
        JTtel.setEnabled(true);
        JTsalario.setEnabled(true);
        JTcpf.setEnabled(true);
        
    }
      public void desabilitaDados(){
        JTnome.setEditable(false);
        JTend.setEditable(false);
        JTtel.setEditable(false);
        JTsalario.setEditable(false);
        JTcpf.setEditable(false);
        
        JTnome.setEnabled(false);
        JTend.setEnabled(false);
        JTtel.setEnabled(false);
        JTsalario.setEnabled(false);
        JTcpf.setEnabled(false);
        
        
    }
     
     
     private void limparCampos(){
        
         JTnome.setText("");
        JTend.setText("");
        JTtel.setText("");
        JTsalario.setText("");
        JTcpf.setText("");
        JTid.setText("");
            
    }
     
     private void alteraProfessor() throws SQLException, Exception {
       if(jTTabela.getSelectedRow()!=-1){
           if(verificadDados()){
               Professor professor = new Professor();
               ProfessorDao dao = new ProfessorDao();
              
               professor.setIdProf(Integer.parseInt(JTid.getText()));
               professor.setNome(JTnome.getText());
               professor.setEndereco(JTend.getText());
               professor.setTelefone(JTtel.getText());
               professor.setCpf(JTcpf.getText());
               professor.setSalario(Float.parseFloat(JTsalario.getText()));

               
               dao.alterar(professor);
               JOptionPane.showMessageDialog(null, "Professor alterado com sucesso!");
           }
           
       }
    } 
        
        public boolean verificadDados(){
        if(!JTnome.getText().equals("")&& !JTend.getText().equals("") && !JTtel.getText().equals("") && !JTsalario.getText().equals("") && !JTid.getText().equals("") && !JTcpf.getText().equals("")){
           return true;
        }else{
           JOptionPane.showMessageDialog(null, "Campos não preenchidos!");
        return false; 
        }       
     
     
     
     
     }  
     
     
}
